// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlMPbf02i0WFOIpSZ7AwfnecHNPfZ9Sh0',
    appId: '1:324192486215:web:4484ea96676acf0bbf4262',
    messagingSenderId: '324192486215',
    projectId: 'authentivator',
    authDomain: 'authentivator.firebaseapp.com',
    databaseURL: 'https://authentivator-default-rtdb.firebaseio.com',
    storageBucket: 'authentivator.appspot.com',
    measurementId: 'G-RKTZYJ34P1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2iy02wxse0F-k4JVQGh-OPn_E2h9RV78',
    appId: '1:324192486215:android:22bdf6137ba65963bf4262',
    messagingSenderId: '324192486215',
    projectId: 'authentivator',
    databaseURL: 'https://authentivator-default-rtdb.firebaseio.com',
    storageBucket: 'authentivator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyBoc5VtJqNgVqzjk7tkdgevL0up3Vi1g',
    appId: '1:324192486215:ios:991a762ba6dde12dbf4262',
    messagingSenderId: '324192486215',
    projectId: 'authentivator',
    databaseURL: 'https://authentivator-default-rtdb.firebaseio.com',
    storageBucket: 'authentivator.appspot.com',
    iosBundleId: 'com.example.authenticator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyBoc5VtJqNgVqzjk7tkdgevL0up3Vi1g',
    appId: '1:324192486215:ios:991a762ba6dde12dbf4262',
    messagingSenderId: '324192486215',
    projectId: 'authentivator',
    databaseURL: 'https://authentivator-default-rtdb.firebaseio.com',
    storageBucket: 'authentivator.appspot.com',
    iosBundleId: 'com.example.authenticator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlMPbf02i0WFOIpSZ7AwfnecHNPfZ9Sh0',
    appId: '1:324192486215:web:0cb5f7323ef5bb35bf4262',
    messagingSenderId: '324192486215',
    projectId: 'authentivator',
    authDomain: 'authentivator.firebaseapp.com',
    databaseURL: 'https://authentivator-default-rtdb.firebaseio.com',
    storageBucket: 'authentivator.appspot.com',
    measurementId: 'G-9HETE3Z1Y9',
  );

}